name: Android

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    timeout-minutes: 20

    steps:
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Specify node version
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install node_modules & Deploy
      run: |
        yarn install --frozen-lockfile
        yarn detox build -c android.emu.release

    - name: Persist test app
      uses: actions/upload-artifact@v2
      with:
        name: app_build
        path: android/app/build/

  test:
    runs-on: macos-latest
    name: Test
    needs: build
    timeout-minutes: 40
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        emu-version: ["system-images;android-25;default;x86_64", "system-images;android-28;google_apis;x86_64", "system-images;android-30;google_apis;x86_64"]
        emu-device-id: ["pixel_xl", "10.1in WXGA (Tablet)"]

    steps:
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Specify node version
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Use specific Java version for sdkmanager to work
      uses: joschi/setup-jdk@v1
      with:
        java-version: 'openjdk8'
        architecture: 'x64'

    - name: Setup Android Emulator
      run: |
        sudo $ANDROID_HOME/tools/bin/avdmanager list device
        echo y | sudo $ANDROID_HOME/tools/bin/sdkmanager --verbose "${{ matrix.emu-version }}"
        $ANDROID_HOME/tools/bin/avdmanager create avd -n emu -k "${{ matrix.emu-version }}" -c 1G -d "${{ matrix.emu-device-id }}" -f

    - uses: actions/download-artifact@v2

    - name: Prepare downloaded files
      run: mv -f app_build/ android/app/build

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install node_modules
      run: |
        yarn install --frozen-lockfile

    - name: Start emulator
      run: |
        export PATH=$PATH:$ANDROID_HOME/platform-tools
        $ANDROID_HOME/emulator/emulator @emu &

    - name: Wait for emulator to be ready
      timeout-minutes: 10
      run: |
        sh ./wait-for-emulator.sh

    - name: Prepare test artifacts folder
      run: mkdir -p ./artifacts

    - name: Test
      timeout-minutes: 20
      run: |
        export PATH=$PATH:$ANDROID_HOME/platform-tools
        yarn detox test -c android.emu.release --headless --record-videos all

    - name: Persist test artifacts
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: detox-artifacts
        path: ./artifacts/
