name: iOS

on: [push, pull_request]

jobs:
  some-job:
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip ios]')"
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout project
      uses: actions/checkout@v1

    - name: Specify node version
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Detox setup
      run: |
        brew tap wix/brew
        brew install applesimutils

    - name: Install node_modules & deploy with specific XCode version
      run: |
        yarn install --frozen-lockfile
        cd ios; pod install
        yarn detox build -c ios.sim.release

    - name: Prepare test artifacts folder
      run: mkdir -p ./artifacts

    - name: iOS test
      timeout-minutes: 15
      run: |
        npx detox clean-framework-cache && npx detox build-framework-cache
        yarn detox test -c ios.sim.release --record-videos all

    - name: Persist test artifacts
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: detox-artifacts
        path: ./artifacts/

